user_per_show: 6
name_max_length: 50
email_max_length: 255
password_min_length: 6
recipe_per_show: 8
truncate_description: 70
img_size_fill: 175
max_file: 5
limit_recipe: 6
hot_recipe: 3
num_category: 5
ingredient_split: 3
img_icon_size: 50
recipe_new: 8
limit_top_user_home: 6
num_top_user: 20
